// ─── LOCAL JSON → DATABASE ROWS ───────────────────────────────────────────────
//
// Converts a "Export backup" file from My View into rows for public.tasks and
// public.area_notes, and emits idempotent SQL to apply them.
//
// Three properties this must have, and which supabase/tests/import.test.mjs
// checks:
//
//  1. **Idempotent.** Applying the same export twice changes nothing the second
//     time. Keyed on the task's own UUID, with a checksum guard on the batch.
//  2. **Non-destructive.** It only ever inserts or updates. It never deletes a
//     row, never truncates, and never touches the browser's localStorage — the
//     phone keeps its copy untouched, and the export file is read-only input.
//  3. **Last-write-wins by updated_at.** Re-importing an *older* export cannot
//     roll back a newer row that is already in the database.
//
// It also refuses to start unless the executing role can bypass RLS. Every
// table carries FORCE row level security with no policies, so RLS applies to
// the table owner too and an ordinary owner's INSERT is refused. Failing on
// line one with a role-shaped message beats failing half-way with a
// data-shaped one.
//
// This module is pure: no network, no credentials, no database connection. The
// SQL it produces is applied by a human in the Supabase SQL editor, or in
// Phase 4 by a server holding the service-role key.

import { createHash } from "node:crypto";

import { normalizeState } from "../../src/lib/storage.js";

export const IMPORT_KIND = "local-json";

/** Empty string means "no owner"; the column is null in that case. */
function nullIfBlank(value) {
  const text = typeof value === "string" ? value.trim() : "";
  return text === "" ? null : text;
}

/**
 * Runs the export through the app's own `normalizeState`, so the rows inherit
 * every guarantee Phase 2 established — v4 UUIDs, re-keyed id collisions, and
 * the sharing invariant — before they are ever offered to the database.
 */
export function toRows(exported) {
  const state = normalizeState(exported);

  const tasks = state.tasks.map((task) => ({
    id: task.id,
    title: task.title,
    notes: task.notes,
    area: task.area,
    status: task.status,
    priority: task.priority,
    due_date: task.dueDate || null,
    due_time: task.dueTime || null,
    owner: nullIfBlank(task.owner),
    visibility: task.visibility,
    created_by: task.createdBy,
    source: task.source,
    created_at: task.createdAt,
    updated_at: task.updatedAt,
    completed_at: task.completedAt,
    import_key: null,
  }));

  const areaNotes = Object.entries(state.areaNotes)
    .filter(([, note]) => note !== "")
    .map(([area, note]) => ({ area, note }));

  return { tasks, areaNotes };
}

/** Stable across key order and formatting, so re-exports of an unchanged board match. */
export function checksum({ tasks, areaNotes }) {
  const canonical = JSON.stringify({
    tasks: [...tasks].sort((a, b) => a.id.localeCompare(b.id)),
    areaNotes: [...areaNotes].sort((a, b) => a.area.localeCompare(b.area)),
  });
  return createHash("sha256").update(canonical).digest("hex");
}

function quote(value) {
  if (value === null || value === undefined) return "null";
  return `'${String(value).replace(/'/g, "''")}'`;
}

const TASK_COLUMNS = [
  "id", "title", "notes", "area", "status", "priority", "due_date", "due_time",
  "owner", "visibility", "created_by", "source", "created_at", "updated_at",
  "completed_at", "import_key",
];

// Everything except the identity and provenance columns, which an import must
// never rewrite on an existing row.
const TASK_UPDATE_COLUMNS = [
  "title", "notes", "area", "status", "priority", "due_date", "due_time",
  "owner", "visibility", "updated_at", "completed_at",
];

/**
 * Builds a single transactional, re-runnable script.
 *
 * @param {object} exported  parsed contents of a Fon's OS backup file
 * @param {{ label?: string }} [options]  a human label recorded on the batch
 */
export function buildImportSql(exported, { label = "" } = {}) {
  const { tasks, areaNotes } = toRows(exported);
  const digest = checksum({ tasks, areaNotes });

  const lines = [
    "-- Generated by supabase/import/generate-sql.mjs — safe to re-run.",
    "-- Inserts and updates only: no row is ever deleted by this script.",
    `-- checksum: ${digest}`,
    `-- tasks: ${tasks.length}  area notes: ${areaNotes.length}`,
    "",
    "begin;",
    "",
    "-- Preflight: public.tasks has FORCE row level security with no policies, so",
    "-- RLS applies to the table owner too. Only a role holding BYPASSRLS can",
    "-- insert. Without this guard the script fails part-way through with a bare",
    "-- \"violates row-level security policy\", which reads like a data problem",
    "-- rather than a wrong-role problem.",
    "do $preflight$",
    "declare",
    "  bypasses boolean;",
    "begin",
    "  select bool_or(r.rolbypassrls) into bypasses",
    "  from pg_roles r",
    "  where pg_has_role(current_user, r.oid, 'USAGE');",
    "",
    "  if not coalesce(bypasses, false) then",
    "    raise exception",
    "      'Fon''s OS import: role % cannot bypass row level security, so every INSERT here would be refused.', current_user",
    "      using errcode = 'insufficient_privilege',",
    "            hint = 'Run this as a role holding BYPASSRLS (on Supabase: service_role, or postgres if it has the attribute). See docs/phase-3-supabase.md, \"Which role may run the import\".';",
    "  end if;",
    "end",
    "$preflight$;",
    "",
    "-- Records the batch. A second run of the same payload hits the unique",
    "-- (kind, checksum) constraint and does nothing.",
    "insert into public.import_batches (kind, source_label, checksum, task_count)",
    `values (${quote(IMPORT_KIND)}, ${quote(label)}, ${quote(digest)}, ${tasks.length})`,
    "on conflict (kind, checksum) do nothing;",
    "",
  ];

  if (tasks.length > 0) {
    lines.push(
      `insert into public.tasks (${TASK_COLUMNS.join(", ")})`,
      "values",
      tasks
        .map((t) => `  (${TASK_COLUMNS.map((c) => quote(t[c])).join(", ")})`)
        .join(",\n"),
      "on conflict (id) do update set",
      TASK_UPDATE_COLUMNS.map((c) => `  ${c} = excluded.${c}`).join(",\n"),
      "-- Never let an older export overwrite a newer row.",
      "where public.tasks.updated_at < excluded.updated_at;",
      "",
    );
  }

  if (areaNotes.length > 0) {
    lines.push(
      "insert into public.area_notes (area, note)",
      "values",
      areaNotes.map((n) => `  (${quote(n.area)}, ${quote(n.note)})`).join(",\n"),
      "on conflict (area) do update set note = excluded.note",
      "where public.area_notes.note is distinct from excluded.note;",
      "",
    );
  }

  lines.push("commit;", "");
  return lines.join("\n");
}
